package enums;

public enum TriggerType {
    ON_CAST,
    TURN_BEGIN,
    TURN_END,
    AFTER_MOVE,
    BEFORE_ATTACKED,
    AFTER_ATTACKED,
    BUFF_ENDED,
    BUFF_ENDED_TURNEND,
    BUFF_DELAY_ENDED,
    BEFORE_MOVE,
    BEFORE_DEATH,
    AFTER_DEATH,
    ON_HEAL,
    UNKNOWN,
}
